// PRODUCTS
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const GET_DETAIL = "GET_DETAIL";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

// SEARCH
export const FETCH_SEARCHED = "FETCH_SEARCHED";
export const CLEAR_SEARCHED = "CLEAR_SEARCHED";

//SHOPPING CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CART = "LOAD_CART";
export const ADD_ORDER = "ADD_ORDER";

// AUTH
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
